export default [
  {
    context: [
      '/template-groups/',
      '/api/',
      '/currentrelease/',
      '/CurrentRelease/',
      '/mars/',
      '/fileroot/',
      '/fr/',
      '/d/',
      '/point/',
      '/original/',
      '/uploader/',
      '/translations/',
      '/produce-files/',
      '/produce-plugin/',
      '/dam2/',
      '/place/',
      '/dam-2-0-backend/',
      '/uploader-service/',
      '/produce/',
      '/tool/',
      '/api-gateway/',
      '/peek/',
      '/integrated-marketing-shop/',
      '/its/',
    ],
    target: 'https://stage.brandmaster.com',
    secure: false,
    logLevel: 'debug',
    changeOrigin: true,
  },
];
